unstable_features = true

attr_fn_like_width = 150
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
chain_width = 100
color = "Auto"
combine_control_expr = true
comment_width = 120
condense_wildcard_suffixes = false
control_brace_style = "AlwaysSameLine"
edition = "2021"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_params_layout = "Tall"
fn_call_width = 150
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_generated_files = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = false
hard_tabs = true
hex_literal_case = "Lower"
imports_indent = "Block"
imports_layout = "Mixed"
indent_style = "Block"
inline_attribute_width = 0
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 180
merge_derives = true
imports_granularity = "Crate"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = false
group_imports = "StdExternalCrate"
reorder_modules = false
skip_children = false
single_line_if_else_max_width = 50
space_after_colon = true
space_before_colon = false
spaces_around_ranges = false
struct_field_align_threshold = 0
struct_lit_single_line = true
struct_lit_width = 40
struct_variant_width = 40
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = false
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = false
wrap_comments = true
